/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AfterTimeoutTrigger {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "timeout")]
    pub timeout: f64,
}

impl AfterTimeoutTrigger {
    pub fn new(r#type: Type, timeout: f64) -> AfterTimeoutTrigger {
        AfterTimeoutTrigger {
            r#type,
            timeout,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "AFTER_TIMEOUT")]
    AfterTimeout,
}

impl Default for Type {
    fn default() -> Type {
        Self::AfterTimeout
    }
}

