/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ComponentPropertyDefinition : A property of a component.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ComponentPropertyDefinition {
    /// Type of this component property.
    #[serde(rename = "type")]
    pub r#type: models::ComponentPropertyType,
    #[serde(rename = "defaultValue")]
    pub default_value: Box<models::ComponentPropertyDefinitionDefaultValue>,
    /// All possible values for this property. Only exists on VARIANT properties.
    #[serde(rename = "variantOptions", skip_serializing_if = "Option::is_none")]
    pub variant_options: Option<Vec<String>>,
    /// Preferred values for this property. Only applicable if type is `INSTANCE_SWAP`.
    #[serde(rename = "preferredValues", skip_serializing_if = "Option::is_none")]
    pub preferred_values: Option<Vec<models::InstanceSwapPreferredValue>>,
}

impl ComponentPropertyDefinition {
    /// A property of a component.
    pub fn new(r#type: models::ComponentPropertyType, default_value: models::ComponentPropertyDefinitionDefaultValue) -> ComponentPropertyDefinition {
        ComponentPropertyDefinition {
            r#type,
            default_value: Box::new(default_value),
            variant_options: None,
            preferred_values: None,
        }
    }
}

