/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ComponentPropertiesTrait {
    /// A mapping of name to `ComponentPropertyDefinition` for every component property on this component. Each property has a type, defaultValue, and other optional values.
    #[serde(rename = "componentPropertyDefinitions", skip_serializing_if = "Option::is_none")]
    pub component_property_definitions: Option<std::collections::HashMap<String, models::ComponentPropertyDefinition>>,
}

impl ComponentPropertiesTrait {
    pub fn new() -> ComponentPropertiesTrait {
        ComponentPropertiesTrait {
            component_property_definitions: None,
        }
    }
}

