/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectorEndpointOneOf {
    /// Node ID that this endpoint attaches to.
    #[serde(rename = "endpointNodeId", skip_serializing_if = "Option::is_none")]
    pub endpoint_node_id: Option<String>,
    /// The position of the endpoint relative to the node.
    #[serde(rename = "position", skip_serializing_if = "Option::is_none")]
    pub position: Option<Box<models::Vector>>,
}

impl ConnectorEndpointOneOf {
    pub fn new() -> ConnectorEndpointOneOf {
        ConnectorEndpointOneOf {
            endpoint_node_id: None,
            position: None,
        }
    }
}

