/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FrameOffset : Position of a comment relative to the frame to which it is attached.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FrameOffset {
    /// Unique id specifying the frame.
    #[serde(rename = "node_id")]
    pub node_id: String,
    /// 2D vector offset within the frame from the top-left corner.
    #[serde(rename = "node_offset")]
    pub node_offset: Box<models::Vector>,
}

impl FrameOffset {
    /// Position of a comment relative to the frame to which it is attached.
    pub fn new(node_id: String, node_offset: models::Vector) -> FrameOffset {
        FrameOffset {
            node_id,
            node_offset: Box::new(node_offset),
        }
    }
}

