/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetFileNodes {
    /// The name of the file as it appears in the editor.
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "role")]
    pub role: models::Role,
    /// The UTC ISO 8601 time at which the file was last modified.
    #[serde(rename = "lastModified")]
    pub last_modified: String,
    #[serde(rename = "editorType")]
    pub editor_type: models::EditorType,
    /// A URL to a thumbnail image of the file.
    #[serde(rename = "thumbnailUrl")]
    pub thumbnail_url: String,
    /// The version number of the file. This number is incremented when a file is modified and can be used to check if the file has changed between requests.
    #[serde(rename = "version")]
    pub version: String,
    /// A mapping from node IDs to node metadata.
    #[serde(rename = "nodes")]
    pub nodes: std::collections::HashMap<String, models::GetFileNodesValue>,
}

impl GetFileNodes {
    pub fn new(name: String, role: models::Role, last_modified: String, editor_type: models::EditorType, thumbnail_url: String, version: String, nodes: std::collections::HashMap<String, models::GetFileNodesValue>) -> GetFileNodes {
        GetFileNodes {
            name,
            role,
            last_modified,
            editor_type,
            thumbnail_url,
            version,
            nodes,
        }
    }
}

