/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LinkAccess : Access policy for users who have the link to the file.
/// Access policy for users who have the link to the file.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LinkAccess {
    #[serde(rename = "view")]
    View,
    #[serde(rename = "edit")]
    Edit,
    #[serde(rename = "org_view")]
    OrgView,
    #[serde(rename = "org_edit")]
    OrgEdit,
    #[serde(rename = "inherit")]
    Inherit,

}

impl std::fmt::Display for LinkAccess {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::View => write!(f, "view"),
            Self::Edit => write!(f, "edit"),
            Self::OrgView => write!(f, "org_view"),
            Self::OrgEdit => write!(f, "org_edit"),
            Self::Inherit => write!(f, "inherit"),
        }
    }
}

impl Default for LinkAccess {
    fn default() -> LinkAccess {
        Self::View
    }
}

