/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LocalVariableCollectionModesInner {
    /// The unique identifier of this mode.
    #[serde(rename = "modeId")]
    pub mode_id: String,
    /// The name of this mode.
    #[serde(rename = "name")]
    pub name: String,
}

impl LocalVariableCollectionModesInner {
    pub fn new(mode_id: String, name: String) -> LocalVariableCollectionModesInner {
        LocalVariableCollectionModesInner {
            mode_id,
            name,
        }
    }
}

