/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Overrides : Fields directly overridden on an instance. Inherited overrides are not included.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Overrides {
    /// A unique ID for a node.
    #[serde(rename = "id")]
    pub id: String,
    /// An array of properties.
    #[serde(rename = "overriddenFields")]
    pub overridden_fields: Vec<String>,
}

impl Overrides {
    /// Fields directly overridden on an instance. Inherited overrides are not included.
    pub fn new(id: String, overridden_fields: Vec<String>) -> Overrides {
        Overrides {
            id,
            overridden_fields,
        }
    }
}

