/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PublishedVariableCollection : A grouping of related Variable objects each with the same modes.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublishedVariableCollection {
    /// The unique identifier of this variable collection.
    #[serde(rename = "id")]
    pub id: String,
    /// The ID of the variable collection that is used by subscribing files. This ID changes every time the variable collection is modified and published.
    #[serde(rename = "subscribed_id")]
    pub subscribed_id: String,
    /// The name of this variable collection.
    #[serde(rename = "name")]
    pub name: String,
    /// The key of this variable collection.
    #[serde(rename = "key")]
    pub key: String,
    /// The UTC ISO 8601 time at which the variable collection was last updated.  This timestamp will change any time a variable in the collection is changed.
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl PublishedVariableCollection {
    /// A grouping of related Variable objects each with the same modes.
    pub fn new(id: String, subscribed_id: String, name: String, key: String, updated_at: String) -> PublishedVariableCollection {
        PublishedVariableCollection {
            id,
            subscribed_id,
            name,
            key,
            updated_at,
        }
    }
}

