/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// User : A description of a user.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct User {
    /// Unique stable id of the user.
    #[serde(rename = "id")]
    pub id: String,
    /// Name of the user.
    #[serde(rename = "handle")]
    pub handle: String,
    /// URL link to the user's profile image.
    #[serde(rename = "img_url")]
    pub img_url: String,
}

impl User {
    /// A description of a user.
    pub fn new(id: String, handle: String, img_url: String) -> User {
        User {
            id,
            handle,
            img_url,
        }
    }
}

