/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VariableCollectionUpdate : An object that contains details about updating a `VariableCollection`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VariableCollectionUpdate {
    /// The action to perform for the variable collection.
    #[serde(rename = "action")]
    pub action: Action,
    /// The id of the variable collection to update.
    #[serde(rename = "id")]
    pub id: String,
    /// The name of this variable collection.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Whether this variable collection is hidden when publishing the current file as a library.
    #[serde(rename = "hiddenFromPublishing", skip_serializing_if = "Option::is_none")]
    pub hidden_from_publishing: Option<bool>,
}

impl VariableCollectionUpdate {
    /// An object that contains details about updating a `VariableCollection`.
    pub fn new(action: Action, id: String) -> VariableCollectionUpdate {
        VariableCollectionUpdate {
            action,
            id,
            name: None,
            hidden_from_publishing: None,
        }
    }
}
/// The action to perform for the variable collection.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Action {
    #[serde(rename = "UPDATE")]
    Update,
}

impl Default for Action {
    fn default() -> Action {
        Self::Update
    }
}

