/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VariableUpdate : An object that contains details about updating a `Variable`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VariableUpdate {
    /// The action to perform for the variable.
    #[serde(rename = "action")]
    pub action: Action,
    /// The id of the variable to update.
    #[serde(rename = "id")]
    pub id: String,
    /// The name of this variable.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The description of this variable.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Whether this variable is hidden when publishing the current file as a library.
    #[serde(rename = "hiddenFromPublishing", skip_serializing_if = "Option::is_none")]
    pub hidden_from_publishing: Option<bool>,
    /// An array of scopes in the UI where this variable is shown. Setting this property will show/hide this variable in the variable picker UI for different fields.
    #[serde(rename = "scopes", skip_serializing_if = "Option::is_none")]
    pub scopes: Option<Vec<models::VariableScope>>,
    #[serde(rename = "codeSyntax", skip_serializing_if = "Option::is_none")]
    pub code_syntax: Option<Box<models::VariableCodeSyntax>>,
}

impl VariableUpdate {
    /// An object that contains details about updating a `Variable`.
    pub fn new(action: Action, id: String) -> VariableUpdate {
        VariableUpdate {
            action,
            id,
            name: None,
            description: None,
            hidden_from_publishing: None,
            scopes: None,
            code_syntax: None,
        }
    }
}
/// The action to perform for the variable.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Action {
    #[serde(rename = "UPDATE")]
    Update,
}

impl Default for Action {
    fn default() -> Action {
        Self::Update
    }
}

