/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VariableDataType : Defines the types of data a VariableData object can hold
/// Defines the types of data a VariableData object can hold
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VariableDataType {
    #[serde(rename = "BOOLEAN")]
    Boolean,
    #[serde(rename = "FLOAT")]
    Float,
    #[serde(rename = "STRING")]
    String,
    #[serde(rename = "COLOR")]
    Color,
    #[serde(rename = "VARIABLE_ALIAS")]
    VariableAlias,
    #[serde(rename = "EXPRESSION")]
    Expression,

}

impl std::fmt::Display for VariableDataType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Boolean => write!(f, "BOOLEAN"),
            Self::Float => write!(f, "FLOAT"),
            Self::String => write!(f, "STRING"),
            Self::Color => write!(f, "COLOR"),
            Self::VariableAlias => write!(f, "VARIABLE_ALIAS"),
            Self::Expression => write!(f, "EXPRESSION"),
        }
    }
}

impl Default for VariableDataType {
    fn default() -> VariableDataType {
        Self::Boolean
    }
}

