/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VariableData : A value to set a variable to during prototyping.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VariableData {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::VariableDataType>,
    #[serde(rename = "resolvedType", skip_serializing_if = "Option::is_none")]
    pub resolved_type: Option<models::VariableResolvedDataType>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<Box<models::VariableDataValue>>,
}

impl VariableData {
    /// A value to set a variable to during prototyping.
    pub fn new() -> VariableData {
        VariableData {
            r#type: None,
            resolved_type: None,
            value: None,
        }
    }
}

