/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VariableCreate : An object that contains details about creating a `Variable`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VariableCreate {
    /// The action to perform for the variable.
    #[serde(rename = "action")]
    pub action: Action,
    /// A temporary id for this variable.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The name of this variable.
    #[serde(rename = "name")]
    pub name: String,
    /// The variable collection that will contain the variable. You can use the temporary id of a variable collection.
    #[serde(rename = "variableCollectionId")]
    pub variable_collection_id: String,
    /// The resolved type of the variable.
    #[serde(rename = "resolvedType")]
    pub resolved_type: ResolvedType,
    /// The description of this variable.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Whether this variable is hidden when publishing the current file as a library.
    #[serde(rename = "hiddenFromPublishing", skip_serializing_if = "Option::is_none")]
    pub hidden_from_publishing: Option<bool>,
    /// An array of scopes in the UI where this variable is shown. Setting this property will show/hide this variable in the variable picker UI for different fields.
    #[serde(rename = "scopes", skip_serializing_if = "Option::is_none")]
    pub scopes: Option<Vec<models::VariableScope>>,
    #[serde(rename = "codeSyntax", skip_serializing_if = "Option::is_none")]
    pub code_syntax: Option<Box<models::VariableCodeSyntax>>,
}

impl VariableCreate {
    /// An object that contains details about creating a `Variable`.
    pub fn new(action: Action, name: String, variable_collection_id: String, resolved_type: ResolvedType) -> VariableCreate {
        VariableCreate {
            action,
            id: None,
            name,
            variable_collection_id,
            resolved_type,
            description: None,
            hidden_from_publishing: None,
            scopes: None,
            code_syntax: None,
        }
    }
}
/// The action to perform for the variable.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Action {
    #[serde(rename = "CREATE")]
    Create,
}

impl Default for Action {
    fn default() -> Action {
        Self::Create
    }
}
/// The resolved type of the variable.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ResolvedType {
    #[serde(rename = "BOOLEAN")]
    Boolean,
    #[serde(rename = "FLOAT")]
    Float,
    #[serde(rename = "STRING")]
    String,
    #[serde(rename = "COLOR")]
    Color,
}

impl Default for ResolvedType {
    fn default() -> ResolvedType {
        Self::Boolean
    }
}

