/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ArcData : Information about the arc properties of an ellipse. 0° is the x axis and increasing angles rotate clockwise.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ArcData {
    /// Start of the sweep in radians.
    #[serde(rename = "startingAngle")]
    pub starting_angle: f64,
    /// End of the sweep in radians.
    #[serde(rename = "endingAngle")]
    pub ending_angle: f64,
    /// Inner radius value between 0 and 1
    #[serde(rename = "innerRadius")]
    pub inner_radius: f64,
}

impl ArcData {
    /// Information about the arc properties of an ellipse. 0° is the x axis and increasing angles rotate clockwise.
    pub fn new(starting_angle: f64, ending_angle: f64, inner_radius: f64) -> ArcData {
        ArcData {
            starting_angle,
            ending_angle,
            inner_radius,
        }
    }
}

