/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BaseNoiseEffect : A noise effect
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseNoiseEffect {
    /// Blend mode of the noise effect
    #[serde(rename = "blendMode")]
    pub blend_mode: models::BlendMode,
    /// The size of the noise effect
    #[serde(rename = "noiseSize")]
    pub noise_size: f64,
    /// The density of the noise effect
    #[serde(rename = "density")]
    pub density: f64,
}

impl BaseNoiseEffect {
    /// A noise effect
    pub fn new(blend_mode: models::BlendMode, noise_size: f64, density: f64) -> BaseNoiseEffect {
        BaseNoiseEffect {
            blend_mode,
            noise_size,
            density,
        }
    }
}

