/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CommentFragment : An object representing a fragment of a comment left by a user, used in the payload of the `FILE_COMMENT` event. Note only ONE of the fields below will be set
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommentFragment {
    /// Comment text that is set if a fragment is text based
    #[serde(rename = "text", skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    /// User id that is set if a fragment refers to a user mention
    #[serde(rename = "mention", skip_serializing_if = "Option::is_none")]
    pub mention: Option<String>,
}

impl CommentFragment {
    /// An object representing a fragment of a comment left by a user, used in the payload of the `FILE_COMMENT` event. Note only ONE of the fields below will be set
    pub fn new() -> CommentFragment {
        CommentFragment {
            text: None,
            mention: None,
        }
    }
}

