/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConditionalBlock : Either the if or else conditional blocks. The if block contains a condition to check. If that condition is met then it will run those list of actions, else it will run the actions in the else block.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConditionalBlock {
    #[serde(rename = "condition", skip_serializing_if = "Option::is_none")]
    pub condition: Option<Box<models::VariableData>>,
    #[serde(rename = "actions")]
    pub actions: Vec<models::Action>,
}

impl ConditionalBlock {
    /// Either the if or else conditional blocks. The if block contains a condition to check. If that condition is met then it will run those list of actions, else it will run the actions in the else block.
    pub fn new(actions: Vec<models::Action>) -> ConditionalBlock {
        ConditionalBlock {
            condition: None,
            actions,
        }
    }
}

