/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectorEndpointOneOf1 {
    /// Node ID that this endpoint attaches to.
    #[serde(rename = "endpointNodeId", skip_serializing_if = "Option::is_none")]
    pub endpoint_node_id: Option<String>,
    /// The magnet type is a string enum.
    #[serde(rename = "magnet", skip_serializing_if = "Option::is_none")]
    pub magnet: Option<Magnet>,
}

impl ConnectorEndpointOneOf1 {
    pub fn new() -> ConnectorEndpointOneOf1 {
        ConnectorEndpointOneOf1 {
            endpoint_node_id: None,
            magnet: None,
        }
    }
}
/// The magnet type is a string enum.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Magnet {
    #[serde(rename = "AUTO")]
    Auto,
    #[serde(rename = "TOP")]
    Top,
    #[serde(rename = "BOTTOM")]
    Bottom,
    #[serde(rename = "LEFT")]
    Left,
    #[serde(rename = "RIGHT")]
    Right,
    #[serde(rename = "CENTER")]
    Center,
}

impl Default for Magnet {
    fn default() -> Magnet {
        Self::Auto
    }
}

