/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConnectorEndpoint : Stores canvas location for a connector start/end point.
/// Stores canvas location for a connector start/end point.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ConnectorEndpoint {
    ConnectorEndpointOneOf(Box<models::ConnectorEndpointOneOf>),
    ConnectorEndpointOneOf1(Box<models::ConnectorEndpointOneOf1>),
}

impl Default for ConnectorEndpoint {
    fn default() -> Self {
        Self::ConnectorEndpointOneOf(Default::default())
    }
}
/// The magnet type is a string enum.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Magnet {
    #[serde(rename = "AUTO")]
    Auto,
    #[serde(rename = "TOP")]
    Top,
    #[serde(rename = "BOTTOM")]
    Bottom,
    #[serde(rename = "LEFT")]
    Left,
    #[serde(rename = "RIGHT")]
    Right,
    #[serde(rename = "CENTER")]
    Center,
}

impl Default for Magnet {
    fn default() -> Magnet {
        Self::Auto
    }
}

