/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EasingEasingFunctionSpring : A spring function that defines the easing.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EasingEasingFunctionSpring {
    #[serde(rename = "mass")]
    pub mass: f64,
    #[serde(rename = "stiffness")]
    pub stiffness: f64,
    #[serde(rename = "damping")]
    pub damping: f64,
}

impl EasingEasingFunctionSpring {
    /// A spring function that defines the easing.
    pub fn new(mass: f64, stiffness: f64, damping: f64) -> EasingEasingFunctionSpring {
        EasingEasingFunctionSpring {
            mass,
            stiffness,
            damping,
        }
    }
}

