/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EditorType : The type of editor associated with this file.
/// The type of editor associated with this file.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EditorType {
    #[serde(rename = "figma")]
    Figma,
    #[serde(rename = "figjam")]
    Figjam,

}

impl std::fmt::Display for EditorType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Figma => write!(f, "figma"),
            Self::Figjam => write!(f, "figjam"),
        }
    }
}

impl Default for EditorType {
    fn default() -> EditorType {
        Self::Figma
    }
}

