/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Expression : Defines the [Expression](https://help.figma.com/hc/en-us/articles/15253194385943) object, which contains a list of `VariableData` objects strung together by operators (`ExpressionFunction`).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Expression {
    #[serde(rename = "expressionFunction")]
    pub expression_function: models::ExpressionFunction,
    #[serde(rename = "expressionArguments")]
    pub expression_arguments: Vec<models::VariableData>,
}

impl Expression {
    /// Defines the [Expression](https://help.figma.com/hc/en-us/articles/15253194385943) object, which contains a list of `VariableData` objects strung together by operators (`ExpressionFunction`).
    pub fn new(expression_function: models::ExpressionFunction, expression_arguments: Vec<models::VariableData>) -> Expression {
        Expression {
            expression_function,
            expression_arguments,
        }
    }
}

