/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FlowStartingPoint : A flow starting point used when launching a prototype to enter Presentation view.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FlowStartingPoint {
    /// Unique identifier specifying the frame.
    #[serde(rename = "nodeId")]
    pub node_id: String,
    /// Name of flow.
    #[serde(rename = "name")]
    pub name: String,
}

impl FlowStartingPoint {
    /// A flow starting point used when launching a prototype to enter Presentation view.
    pub fn new(node_id: String, name: String) -> FlowStartingPoint {
        FlowStartingPoint {
            node_id,
            name,
        }
    }
}

