/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject2 {
    /// For successful requests, this value is always `null`.
    #[serde(rename = "err", deserialize_with = "Option::deserialize")]
    pub err: Option<serde_json::Value>,
    /// A map from node IDs to URLs of the rendered images.
    #[serde(rename = "images")]
    pub images: std::collections::HashMap<String, String>,
}

impl InlineObject2 {
    pub fn new(err: Option<serde_json::Value>, images: std::collections::HashMap<String, String>) -> InlineObject2 {
        InlineObject2 {
            err,
            images,
        }
    }
}

