/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObjectBranchesInner {
    /// The key of the branch.
    #[serde(rename = "key")]
    pub key: String,
    /// The name of the branch.
    #[serde(rename = "name")]
    pub name: String,
    /// A URL to a thumbnail image of the branch.
    #[serde(rename = "thumbnail_url")]
    pub thumbnail_url: String,
    /// The UTC ISO 8601 time at which the branch was last modified.
    #[serde(rename = "last_modified")]
    pub last_modified: String,
}

impl InlineObjectBranchesInner {
    pub fn new(key: String, name: String, thumbnail_url: String, last_modified: String) -> InlineObjectBranchesInner {
        InlineObjectBranchesInner {
            key,
            name,
            thumbnail_url,
            last_modified,
        }
    }
}

