/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject1NodesValue {
    #[serde(rename = "document")]
    pub document: Box<models::Node>,
    /// A mapping from component IDs to component metadata.
    #[serde(rename = "components")]
    pub components: std::collections::HashMap<String, models::Component>,
    /// A mapping from component set IDs to component set metadata.
    #[serde(rename = "componentSets")]
    pub component_sets: std::collections::HashMap<String, models::ComponentSet>,
    /// The version of the file schema that this file uses.
    #[serde(rename = "schemaVersion")]
    pub schema_version: f64,
    /// A mapping from style IDs to style metadata.
    #[serde(rename = "styles")]
    pub styles: std::collections::HashMap<String, models::Style>,
}

impl InlineObject1NodesValue {
    pub fn new(document: models::Node, components: std::collections::HashMap<String, models::Component>, component_sets: std::collections::HashMap<String, models::ComponentSet>, schema_version: f64, styles: std::collections::HashMap<String, models::Style>) -> InlineObject1NodesValue {
        InlineObject1NodesValue {
            document: Box::new(document),
            components,
            component_sets,
            schema_version,
            styles,
        }
    }
}

