/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InstanceSwapPreferredValue : Instance swap preferred value.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstanceSwapPreferredValue {
    /// Type of node for this preferred value.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Key of this component or component set.
    #[serde(rename = "key")]
    pub key: String,
}

impl InstanceSwapPreferredValue {
    /// Instance swap preferred value.
    pub fn new(r#type: Type, key: String) -> InstanceSwapPreferredValue {
        InstanceSwapPreferredValue {
            r#type,
            key,
        }
    }
}
/// Type of node for this preferred value.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "COMPONENT")]
    Component,
    #[serde(rename = "COMPONENT_SET")]
    ComponentSet,
}

impl Default for Type {
    fn default() -> Type {
        Self::Component
    }
}

