/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IsLayerTraitBoundVariablesRectangleCornerRadii {
    #[serde(rename = "RECTANGLE_TOP_LEFT_CORNER_RADIUS", skip_serializing_if = "Option::is_none")]
    pub rectangle_top_left_corner_radius: Option<Box<models::VariableAlias>>,
    #[serde(rename = "RECTANGLE_TOP_RIGHT_CORNER_RADIUS", skip_serializing_if = "Option::is_none")]
    pub rectangle_top_right_corner_radius: Option<Box<models::VariableAlias>>,
    #[serde(rename = "RECTANGLE_BOTTOM_LEFT_CORNER_RADIUS", skip_serializing_if = "Option::is_none")]
    pub rectangle_bottom_left_corner_radius: Option<Box<models::VariableAlias>>,
    #[serde(rename = "RECTANGLE_BOTTOM_RIGHT_CORNER_RADIUS", skip_serializing_if = "Option::is_none")]
    pub rectangle_bottom_right_corner_radius: Option<Box<models::VariableAlias>>,
}

impl IsLayerTraitBoundVariablesRectangleCornerRadii {
    pub fn new() -> IsLayerTraitBoundVariablesRectangleCornerRadii {
        IsLayerTraitBoundVariablesRectangleCornerRadii {
            rectangle_top_left_corner_radius: None,
            rectangle_top_right_corner_radius: None,
            rectangle_bottom_left_corner_radius: None,
            rectangle_bottom_right_corner_radius: None,
        }
    }
}

