/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LayoutGridBoundVariables : The variables bound to a particular field on this layout grid
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LayoutGridBoundVariables {
    #[serde(rename = "gutterSize", skip_serializing_if = "Option::is_none")]
    pub gutter_size: Option<Box<models::VariableAlias>>,
    #[serde(rename = "numSections", skip_serializing_if = "Option::is_none")]
    pub num_sections: Option<Box<models::VariableAlias>>,
    #[serde(rename = "sectionSize", skip_serializing_if = "Option::is_none")]
    pub section_size: Option<Box<models::VariableAlias>>,
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<Box<models::VariableAlias>>,
}

impl LayoutGridBoundVariables {
    /// The variables bound to a particular field on this layout grid
    pub fn new() -> LayoutGridBoundVariables {
        LayoutGridBoundVariables {
            gutter_size: None,
            num_sections: None,
            section_size: None,
            offset: None,
        }
    }
}

