/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MeasurementOffsetInner : Measurement offset relative to the inside of the start node
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MeasurementOffsetInner {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "relative")]
    pub relative: f64,
}

impl MeasurementOffsetInner {
    /// Measurement offset relative to the inside of the start node
    pub fn new(r#type: Type, relative: f64) -> MeasurementOffsetInner {
        MeasurementOffsetInner {
            r#type,
            relative,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "INNER")]
    Inner,
}

impl Default for Type {
    fn default() -> Type {
        Self::Inner
    }
}

