/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OnMediaHitTrigger {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "mediaHitTime")]
    pub media_hit_time: f64,
}

impl OnMediaHitTrigger {
    pub fn new(r#type: Type, media_hit_time: f64) -> OnMediaHitTrigger {
        OnMediaHitTrigger {
            r#type,
            media_hit_time,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "ON_MEDIA_HIT")]
    OnMediaHit,
}

impl Default for Type {
    fn default() -> Type {
        Self::OnMediaHit
    }
}

