/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OpenUrlAction : An action that opens a URL.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpenUrlAction {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "url")]
    pub url: String,
}

impl OpenUrlAction {
    /// An action that opens a URL.
    pub fn new(r#type: Type, url: String) -> OpenUrlAction {
        OpenUrlAction {
            r#type,
            url,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "URL")]
    Url,
}

impl Default for Type {
    fn default() -> Type {
        Self::Url
    }
}

