/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Rectangle : A rectangle that expresses a bounding box in absolute coordinates.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Rectangle {
    /// X coordinate of top left corner of the rectangle.
    #[serde(rename = "x")]
    pub x: f64,
    /// Y coordinate of top left corner of the rectangle.
    #[serde(rename = "y")]
    pub y: f64,
    /// Width of the rectangle.
    #[serde(rename = "width")]
    pub width: f64,
    /// Height of the rectangle.
    #[serde(rename = "height")]
    pub height: f64,
}

impl Rectangle {
    /// A rectangle that expresses a bounding box in absolute coordinates.
    pub fn new(x: f64, y: f64, width: f64, height: f64) -> Rectangle {
        Rectangle {
            x,
            y,
            width,
            height,
        }
    }
}

