/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Rgb : An RGB color
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Rgb {
    /// Red channel value, between 0 and 1.
    #[serde(rename = "r")]
    pub r: f64,
    /// Green channel value, between 0 and 1.
    #[serde(rename = "g")]
    pub g: f64,
    /// Blue channel value, between 0 and 1.
    #[serde(rename = "b")]
    pub b: f64,
}

impl Rgb {
    /// An RGB color
    pub fn new(r: f64, g: f64, b: f64) -> Rgb {
        Rgb {
            r,
            g,
            b,
        }
    }
}

