/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SetVariableModeAction : Sets a variable to a specific mode.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetVariableModeAction {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "variableCollectionId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub variable_collection_id: Option<Option<String>>,
    #[serde(rename = "variableModeId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub variable_mode_id: Option<Option<String>>,
}

impl SetVariableModeAction {
    /// Sets a variable to a specific mode.
    pub fn new(r#type: Type) -> SetVariableModeAction {
        SetVariableModeAction {
            r#type,
            variable_collection_id: None,
            variable_mode_id: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "SET_VARIABLE_MODE")]
    SetVariableMode,
}

impl Default for Type {
    fn default() -> Type {
        Self::SetVariableMode
    }
}

