/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SimpleTransition : Describes an animation used when navigating in a prototype.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SimpleTransition {
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The duration of the transition in milliseconds.
    #[serde(rename = "duration")]
    pub duration: f64,
    /// The easing curve of the transition.
    #[serde(rename = "easing")]
    pub easing: Box<models::Easing>,
}

impl SimpleTransition {
    /// Describes an animation used when navigating in a prototype.
    pub fn new(r#type: Type, duration: f64, easing: models::Easing) -> SimpleTransition {
        SimpleTransition {
            r#type,
            duration,
            easing: Box::new(easing),
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "DISSOLVE")]
    Dissolve,
    #[serde(rename = "SMART_ANIMATE")]
    SmartAnimate,
    #[serde(rename = "SCROLL_ANIMATE")]
    ScrollAnimate,
}

impl Default for Type {
    fn default() -> Type {
        Self::Dissolve
    }
}

