/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StyleType : The type of style
/// The type of style
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StyleType {
    #[serde(rename = "FILL")]
    Fill,
    #[serde(rename = "TEXT")]
    Text,
    #[serde(rename = "EFFECT")]
    Effect,
    #[serde(rename = "GRID")]
    Grid,

}

impl std::fmt::Display for StyleType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Fill => write!(f, "FILL"),
            Self::Text => write!(f, "TEXT"),
            Self::Effect => write!(f, "EFFECT"),
            Self::Grid => write!(f, "GRID"),
        }
    }
}

impl Default for StyleType {
    fn default() -> StyleType {
        Self::Fill
    }
}

