/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TypeStyleAllOfBoundVariables : The variables bound to a particular field on this style
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TypeStyleAllOfBoundVariables {
    #[serde(rename = "fontFamily", skip_serializing_if = "Option::is_none")]
    pub font_family: Option<Box<models::VariableAlias>>,
    #[serde(rename = "fontSize", skip_serializing_if = "Option::is_none")]
    pub font_size: Option<Box<models::VariableAlias>>,
    #[serde(rename = "fontStyle", skip_serializing_if = "Option::is_none")]
    pub font_style: Option<Box<models::VariableAlias>>,
    #[serde(rename = "fontWeight", skip_serializing_if = "Option::is_none")]
    pub font_weight: Option<Box<models::VariableAlias>>,
    #[serde(rename = "letterSpacing", skip_serializing_if = "Option::is_none")]
    pub letter_spacing: Option<Box<models::VariableAlias>>,
    #[serde(rename = "lineHeight", skip_serializing_if = "Option::is_none")]
    pub line_height: Option<Box<models::VariableAlias>>,
    #[serde(rename = "paragraphSpacing", skip_serializing_if = "Option::is_none")]
    pub paragraph_spacing: Option<Box<models::VariableAlias>>,
    #[serde(rename = "paragraphIndent", skip_serializing_if = "Option::is_none")]
    pub paragraph_indent: Option<Box<models::VariableAlias>>,
}

impl TypeStyleAllOfBoundVariables {
    /// The variables bound to a particular field on this style
    pub fn new() -> TypeStyleAllOfBoundVariables {
        TypeStyleAllOfBoundVariables {
            font_family: None,
            font_size: None,
            font_style: None,
            font_weight: None,
            letter_spacing: None,
            line_height: None,
            paragraph_spacing: None,
            paragraph_indent: None,
        }
    }
}

