/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateMediaRuntimeAction : An action that affects a video node in the Figma viewer. For example, to play, pause, or skip.
/// An action that affects a video node in the Figma viewer. For example, to play, pause, or skip.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateMediaRuntimeAction {
    UpdateMediaRuntimeActionOneOf(Box<models::UpdateMediaRuntimeActionOneOf>),
    UpdateMediaRuntimeActionOneOf1(Box<models::UpdateMediaRuntimeActionOneOf1>),
    UpdateMediaRuntimeActionOneOf2(Box<models::UpdateMediaRuntimeActionOneOf2>),
}

impl Default for UpdateMediaRuntimeAction {
    fn default() -> Self {
        Self::UpdateMediaRuntimeActionOneOf(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "UPDATE_MEDIA_RUNTIME")]
    UpdateMediaRuntime,
}

impl Default for Type {
    fn default() -> Type {
        Self::UpdateMediaRuntime
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MediaAction {
    #[serde(rename = "SKIP_TO")]
    SkipTo,
}

impl Default for MediaAction {
    fn default() -> MediaAction {
        Self::SkipTo
    }
}

