/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VariableModeDelete : An object that contains details about deleting a `VariableMode`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VariableModeDelete {
    /// The action to perform for the variable mode.
    #[serde(rename = "action")]
    pub action: Action,
    /// The id of the variable mode to delete.
    #[serde(rename = "id")]
    pub id: String,
}

impl VariableModeDelete {
    /// An object that contains details about deleting a `VariableMode`.
    pub fn new(action: Action, id: String) -> VariableModeDelete {
        VariableModeDelete {
            action,
            id,
        }
    }
}
/// The action to perform for the variable mode.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Action {
    #[serde(rename = "DELETE")]
    Delete,
}

impl Default for Action {
    fn default() -> Action {
        Self::Delete
    }
}

