/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VariableCodeSyntax : An object containing platform-specific code syntax definitions for a variable. All platforms are optional.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VariableCodeSyntax {
    #[serde(rename = "WEB", skip_serializing_if = "Option::is_none")]
    pub web: Option<String>,
    #[serde(rename = "ANDROID", skip_serializing_if = "Option::is_none")]
    pub android: Option<String>,
    #[serde(rename = "iOS", skip_serializing_if = "Option::is_none")]
    pub i_os: Option<String>,
}

impl VariableCodeSyntax {
    /// An object containing platform-specific code syntax definitions for a variable. All platforms are optional.
    pub fn new() -> VariableCodeSyntax {
        VariableCodeSyntax {
            web: None,
            android: None,
            i_os: None,
        }
    }
}

