/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.31.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VariableResolvedDataType : Defines the types of data a VariableData object can eventually equal
/// Defines the types of data a VariableData object can eventually equal
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VariableResolvedDataType {
    #[serde(rename = "BOOLEAN")]
    Boolean,
    #[serde(rename = "FLOAT")]
    Float,
    #[serde(rename = "STRING")]
    String,
    #[serde(rename = "COLOR")]
    Color,

}

impl std::fmt::Display for VariableResolvedDataType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Boolean => write!(f, "BOOLEAN"),
            Self::Float => write!(f, "FLOAT"),
            Self::String => write!(f, "STRING"),
            Self::Color => write!(f, "COLOR"),
        }
    }
}

impl Default for VariableResolvedDataType {
    fn default() -> VariableResolvedDataType {
        Self::Boolean
    }
}

